import { readFile } from 'node:fs/promises'
import { expect, test } from '@playwright/test'
import { captureBrowserDiagnostics, createProject, createStandardWorkspace, expectNoHorizontalOverflow, openWorkspaceCenter, waitForApp } from './helpers'

test('local PDF, project space, and editable task deadlines survive reload', async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000)
  const diagnostics = captureBrowserDiagnostics(page)
  await page.goto('/')
  await waitForApp(page)
  await createStandardWorkspace(page, 'DEMO E2E feedback workspace')
  await createProject(page, 'DEMO E2E first project')
  await createProject(page, 'DEMO E2E second project')
  const scope = page.getByRole('combobox', { name: '项目空间', exact: true })
  const firstProjectId = await scope.locator('option').filter({ hasText: 'DEMO E2E first project' }).getAttribute('value')
  const secondProjectId = await scope.locator('option').filter({ hasText: 'DEMO E2E second project' }).getAttribute('value')
  expect(firstProjectId).toBeTruthy()
  expect(secondProjectId).toBeTruthy()
  await scope.selectOption({ label: 'DEMO E2E second project' })
  await expect(scope).toHaveValue(secondProjectId!)
  await page.goto('/#/literature?view=all')
  await waitForApp(page)
  await page.getByRole('button', { name: '添加文献', exact: true }).click()
  const otherLiterature = page.getByRole('dialog', { name: '添加文献', exact: true })
  await otherLiterature.getByLabel('标题', { exact: false }).fill('DEMO E2E second-project source')
  await otherLiterature.getByLabel('作者', { exact: false }).fill('DEMO E2E synthetic author')
  await otherLiterature.getByLabel('为何阅读？', { exact: false }).fill('DEMO E2E retain other-project rationale')
  await expect(otherLiterature.getByLabel('项目', { exact: false })).toBeDisabled()
  await otherLiterature.getByRole('button', { name: '加入队列', exact: true }).click()
  await expect(otherLiterature).toBeHidden()
  await expect(page.getByText('DEMO E2E second-project source', { exact: true })).toBeVisible()
  await page.goto('/#/?view=tasks')
  await waitForApp(page)
  await page.getByRole('button', { name: '添加研究任务', exact: true }).click()
  const otherTask = page.getByRole('dialog', { name: '添加研究任务', exact: true })
  await otherTask.getByLabel('任务', { exact: false }).fill('DEMO E2E second-project task')
  await otherTask.getByLabel('截止日期', { exact: true }).fill('2098-01-10')
  await otherTask.getByLabel('备注', { exact: true }).fill('DEMO E2E retain other-project notes')
  await otherTask.getByRole('button', { name: '添加任务', exact: true }).click()
  await expect(otherTask).toBeHidden()
  await scope.selectOption({ label: 'DEMO E2E first project' })
  await expect(scope).toHaveValue(firstProjectId!)

  await page.goto('/#/literature?view=cited')
  await waitForApp(page)
  const fixture = Buffer.from('%PDF-1.4\nDEMO E2E synthetic fixture\n%%EOF')
  const chooserEvent = page.waitForEvent('filechooser')
  await page.getByRole('button', { name: '添加 PDF', exact: true }).click()
  await (await chooserEvent).setFiles({ name: 'DEMO-E2E-source.pdf', mimeType: 'application/pdf', buffer: fixture })
  const literature = page.getByRole('dialog', { name: '添加文献', exact: true })
  await expect(literature.getByLabel('标题', { exact: false })).toHaveValue('DEMO-E2E-source')
  await expect(literature.getByLabel('项目', { exact: false })).toBeDisabled()
  await literature.getByLabel('为何阅读？', { exact: false }).fill('DEMO E2E synthetic research rationale')
  await literature.getByRole('button', { name: '加入队列', exact: true }).click()
  await expect(literature).toBeHidden()
  await expect(page.getByText('DEMO-E2E-source', { exact: true })).toBeVisible()
  await expect(page).toHaveURL(/view=all/)
  await page.reload()
  await waitForApp(page)
  await expect(scope).toHaveValue(firstProjectId!)
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('link', { name: '下载 DEMO-E2E-source.pdf', exact: true }).click()
  const download = await downloadEvent
  expect(await readFile((await download.path())!)).toEqual(fixture)
  await expectNoHorizontalOverflow(page)

  const sourceCard = page.locator('article').filter({ hasText: 'DEMO-E2E-source' })
  await sourceCard.getByRole('button', { name: '查看／编辑', exact: true }).click()
  const editLiterature = page.getByRole('dialog', { name: '查看与编辑文献', exact: true })
  await expect(editLiterature.getByLabel('为何阅读？', { exact: false })).toHaveValue('DEMO E2E synthetic research rationale')
  await editLiterature.getByLabel('为何阅读？', { exact: false }).fill('DEMO E2E revised research rationale')
  await editLiterature.getByRole('button', { name: '保存', exact: true }).click()
  await expect(editLiterature).toBeHidden()

  await scope.selectOption({ label: 'DEMO E2E second project' })
  await expect(scope).toHaveValue(secondProjectId!)
  await expect(page.getByText('DEMO-E2E-source', { exact: true })).toBeHidden()
  await expect(page.getByText('DEMO E2E second-project source', { exact: true })).toBeVisible()
  await scope.selectOption('')
  await expect(scope).toHaveValue('')
  await expect(page.getByText('DEMO-E2E-source', { exact: true })).toBeVisible()
  await scope.selectOption({ label: 'DEMO E2E first project' })
  await expect(scope).toHaveValue(firstProjectId!)

  await page.goto('/#/?view=tasks')
  await waitForApp(page)
  await page.getByRole('button', { name: '添加研究任务', exact: true }).click()
  const task = page.getByRole('dialog', { name: '添加研究任务', exact: true })
  await task.getByLabel('任务', { exact: false }).fill('DEMO E2E review manuscript')
  await task.getByLabel('截止日期', { exact: true }).fill('2099-01-10')
  await task.getByLabel('备注', { exact: true }).fill('DEMO E2E synthetic notes')
  await task.getByRole('button', { name: '添加任务', exact: true }).click()
  await expect(task).toBeHidden()
  await expect(page.getByText(/截止：.*2099/)).toBeVisible()
  const taskRow = page.getByRole('button', { name: /^DEMO E2E review manuscript/ })
  await taskRow.click()
  await expect(taskRow).toHaveClass(/check-row--done/)
  await page.getByRole('button', { name: '查看与编辑任务：DEMO E2E review manuscript', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '查看与编辑任务', exact: true })
  await expect(edit.getByLabel('备注')).toHaveValue('DEMO E2E synthetic notes')
  await edit.getByLabel('截止日期').fill('2099-01-12')
  await edit.getByRole('button', { name: '保存', exact: true }).click()
  await expect(edit).toBeHidden()
  await page.reload()
  await waitForApp(page)
  await expect(page.getByText(/截止：.*2099/)).toBeVisible()
  await page.getByRole('button', { name: '查看与编辑任务：DEMO E2E review manuscript', exact: true }).click()
  await expect(page.getByRole('dialog').getByLabel('截止日期')).toHaveValue('2099-01-12')
  await expect(page.getByRole('dialog').getByLabel('备注')).toHaveValue('DEMO E2E synthetic notes')
  await page.getByRole('dialog').getByRole('button', { name: '取消', exact: true }).click()
  await expect(taskRow).toHaveClass(/check-row--done/)
  await expectNoHorizontalOverflow(page)

  await scope.selectOption({ label: 'DEMO E2E second project' })
  await expect(scope).toHaveValue(secondProjectId!)
  await page.reload()
  await waitForApp(page)
  await expect(page.getByRole('button', { name: /^DEMO E2E second-project task/ })).toBeVisible()
  await expect(page.getByRole('button', { name: /^DEMO E2E review manuscript/ })).toBeHidden()
  await page.goto('/#/literature?view=all')
  await waitForApp(page)
  await expect(page.getByText('DEMO E2E second-project source', { exact: true })).toBeVisible()
  await expect(page.getByText('DEMO-E2E-source', { exact: true })).toBeHidden()
  await scope.selectOption({ label: 'DEMO E2E first project' })
  await expect(scope).toHaveValue(firstProjectId!)
  await expect(page.getByText('DEMO E2E revised research rationale', { exact: true })).toBeVisible()

  const center = await openWorkspaceCenter(page)
  await center.getByRole('tab', { name: '备份与恢复', exact: true }).click()
  await center.getByRole('button', { name: '导出明文 JSON', exact: true }).click()
  const warning = page.getByRole('dialog', { name: '导出可直接读取的明文？', exact: true })
  const backupEvent = page.waitForEvent('download')
  await warning.getByRole('button', { name: '导出明文 JSON', exact: true }).click()
  const backup = await backupEvent
  const snapshot = JSON.parse(await readFile((await backup.path())!, 'utf8'))
  expect(snapshot.projects.map((project: { title: string }) => project.title).sort()).toEqual([
    'DEMO E2E first project',
    'DEMO E2E second project',
  ])
  const source = snapshot.literature.find((item: { title: string }) => item.title === 'DEMO-E2E-source')
  expect(source.projectId).toBe(firstProjectId)
  expect(source.localPdf).toEqual({ fileName: 'DEMO-E2E-source.pdf', size: fixture.length, base64: fixture.toString('base64') })
  expect(source.whyRead).toBe('DEMO E2E revised research rationale')
  expect(snapshot.literature.find((item: { title: string }) => item.title === 'DEMO E2E second-project source')).toMatchObject({
    projectId: secondProjectId,
    whyRead: 'DEMO E2E retain other-project rationale',
    authors: ['DEMO E2E synthetic author'],
  })
  expect(snapshot.tasks.find((item: { title: string }) => item.title === 'DEMO E2E review manuscript')).toMatchObject({
    projectId: firstProjectId, dueDate: '2099-01-12', status: 'Done', notes: 'DEMO E2E synthetic notes',
  })
  expect(snapshot.tasks.find((item: { title: string }) => item.title === 'DEMO E2E second-project task')).toMatchObject({
    projectId: secondProjectId, dueDate: '2098-01-10', status: 'To Do', notes: 'DEMO E2E retain other-project notes',
  })
  expect(snapshot.version).toBe(6)
  expect(snapshot.literature).toHaveLength(2)
  expect(snapshot.tasks).toHaveLength(2)
  await expect(warning).toBeHidden()
  await center.getByRole('button', { name: '关闭对话框', exact: true }).click()
  await expect(center).toBeHidden()
  expect(diagnostics).toEqual({ pageErrors: [], consoleProblems: [] })
})

test('encrypted PDF storage and authenticated backup restore retain exact attachment bytes', async ({ page }, testInfo) => {
  testInfo.setTimeout(120_000)
  const diagnostics = captureBrowserDiagnostics(page)
  const workspacePassphrase = 'DEMO E2E isolated encrypted PDF passphrase'
  const backupPassphrase = 'DEMO E2E isolated PDF backup passphrase'
  const restoredPassphrase = 'DEMO E2E isolated restored PDF passphrase'
  const fixture = Buffer.from('%PDF-1.4\nDEMO E2E encrypted synthetic fixture\n%%EOF')
  await page.goto('/')
  await waitForApp(page)
  let center = await openWorkspaceCenter(page)
  await center.getByRole('button', { name: '新建工作台', exact: true }).click()
  const create = page.getByRole('dialog', { name: '创建本地工作台', exact: true })
  await create.getByLabel('工作台名称').fill('DEMO E2E encrypted PDF workspace')
  await create.getByRole('radio', { name: /加密本地工作台/ }).check()
  await create.getByLabel('口令', { exact: true }).fill(workspacePassphrase)
  await create.getByLabel('再次输入口令').fill(workspacePassphrase)
  await create.getByRole('checkbox', { name: /无法恢复遗失的口令/ }).check()
  await create.getByRole('button', { name: '创建工作台', exact: true }).click()
  await expect(create).toBeHidden()
  await waitForApp(page)
  await createProject(page, 'DEMO E2E encrypted PDF project')
  const encryptedScope = page.getByRole('combobox', { name: '项目空间', exact: true })
  const [encryptedProjectId] = await encryptedScope.selectOption({ label: 'DEMO E2E encrypted PDF project' })
  await expect(encryptedScope).toHaveValue(encryptedProjectId!)
  await page.goto('/#/literature?view=all')
  await waitForApp(page)
  await page.getByRole('button', { name: '添加文献', exact: true }).click()
  const literature = page.getByRole('dialog', { name: '添加文献', exact: true })
  await literature.getByLabel('本地 PDF', { exact: true }).setInputFiles({
    name: 'DEMO-E2E-encrypted.pdf', mimeType: 'application/pdf', buffer: fixture,
  })
  await expect(literature.getByLabel('标题', { exact: false })).toHaveValue('DEMO-E2E-encrypted')
  await literature.getByLabel('为何阅读？', { exact: false }).fill('DEMO E2E encrypted synthetic rationale')
  await literature.getByRole('button', { name: '加入队列', exact: true }).click()
  await expect(literature).toBeHidden()
  await page.getByRole('button', { name: '锁定此工作台', exact: true }).click()
  await expect(page.getByRole('heading', { name: '加密工作台已锁定', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: '加密工作台已锁定', exact: true })).toBeVisible()
  await page.getByLabel('工作台口令', { exact: true }).fill(workspacePassphrase)
  await page.getByRole('button', { name: '解锁工作台', exact: true }).click()
  await waitForApp(page)
  let downloadEvent = page.waitForEvent('download')
  await page.getByRole('link', { name: '下载 DEMO-E2E-encrypted.pdf', exact: true }).click()
  expect(await readFile((await (await downloadEvent).path())!)).toEqual(fixture)
  await expectNoHorizontalOverflow(page)

  center = await openWorkspaceCenter(page)
  await center.getByRole('tab', { name: '备份与恢复', exact: true }).click()
  await center.getByRole('button', { name: '导出加密备份', exact: true }).click()
  const exportDialog = page.getByRole('dialog', { name: '创建加密备份', exact: true })
  await exportDialog.getByLabel('备份口令', { exact: true }).fill(backupPassphrase)
  await exportDialog.getByLabel('再次输入备份口令', { exact: true }).fill(backupPassphrase)
  downloadEvent = page.waitForEvent('download')
  await exportDialog.getByRole('button', { name: '生成加密备份', exact: true }).click()
  const backup = await downloadEvent
  const backupPath = (await backup.path())!
  const wrapper = await readFile(backupPath, 'utf8')
  expect(backup.suggestedFilename()).toMatch(/\.sociologydesk$/)
  expect(Object.keys(JSON.parse(wrapper)).sort()).toEqual(['ciphertext', 'iv', 'protected'])
  expect(wrapper).not.toContain('DEMO-E2E-encrypted.pdf')
  expect(wrapper).not.toContain(fixture.toString('base64'))
  expect(wrapper).not.toContain(backupPassphrase)
  await expect(exportDialog).toBeHidden()
  await center.getByRole('button', { name: '导入加密备份', exact: true }).click()
  const restore = page.getByRole('dialog', { name: '把加密备份恢复到新工作台', exact: true })
  await restore.getByLabel('加密 .sociologydesk 文件', { exact: true }).setInputFiles(backupPath)
  await restore.getByLabel('备份口令', { exact: true }).fill(backupPassphrase)
  await restore.getByLabel('新工作台口令', { exact: true }).fill(restoredPassphrase)
  await restore.getByLabel('再次输入新工作台口令', { exact: true }).fill(restoredPassphrase)
  await restore.getByRole('checkbox', { name: /无法恢复新工作台口令/ }).check()
  await restore.getByRole('button', { name: '检查导入预检', exact: true }).click()
  await expect(restore.getByText('未写入', { exact: true })).toBeVisible()
  await restore.getByRole('button', { name: '恢复到新工作台', exact: true }).click()
  await expect(restore).toBeHidden()
  await expect(center).toBeHidden()
  await waitForApp(page)
  await page.getByRole('button', { name: '锁定此工作台', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('heading', { name: '加密工作台已锁定', exact: true })).toBeVisible()
  await page.getByLabel('工作台口令', { exact: true }).fill(restoredPassphrase)
  await page.getByRole('button', { name: '解锁工作台', exact: true }).click()
  await waitForApp(page)
  await page.goto('/#/literature?view=all')
  await waitForApp(page)
  await expect(page.getByText('DEMO E2E encrypted synthetic rationale', { exact: true })).toBeVisible()
  downloadEvent = page.waitForEvent('download')
  await page.getByRole('link', { name: '下载 DEMO-E2E-encrypted.pdf', exact: true }).click()
  expect(await readFile((await (await downloadEvent).path())!)).toEqual(fixture)
  await expectNoHorizontalOverflow(page)
  expect(diagnostics).toEqual({ pageErrors: [], consoleProblems: [] })
})
